# This is to actually deploy the module 
name: Deploy Viam Module

on:
  push:
    branches:
      - main # or master, depending on your default branch
    tags:
      - 'v*' # Run on tag pushes like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build and publish the module to the Viam Registry
      - name: Build and Publish Viam Module
        uses: viamrobotics/build-action@v1
        with:
          # The VIAM_API_KEY secret must be set in your GitHub repository settings
          api-key: ${{ secrets.VIAM_API_KEY }}
          # The path to your meta.json file
          meta-json-path: meta.json
          # The path to your run.sh file
          run-sh-path: run.sh
          # The path to your requirements.txt file
          requirements-txt-path: requirements.txt
          # The path to your module source code directory
          source-path: src
          # The target architectures to build for (common for Raspberry Pi)
          platforms: linux/arm64,linux/amd64
