name: Deploy Viam Module

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Viam CLI
        run: |
          sudo curl -o /usr/local/bin/viam https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-stable-linux-amd64
          sudo chmod +x /usr/local/bin/viam
          viam version

      - name: Build module
        run: make module.tar.gz

      - name: Authenticate with Viam
        env:
          VIAM_API_KEY_ID: ${{ secrets.VIAM_API_KEY_ID }}
          VIAM_API_KEY: ${{ secrets.VIAM_API_KEY }}
        run: |
          echo "$VIAM_API_KEY" | viam login api-key --key-id="$VIAM_API_KEY_ID"

      - name: Upload module to Viam
        run: |
          echo "Uploading module with version ${{ github.event.release.tag_name || 'dev' }}"
          viam module upload --version ${{ github.event.release.tag_name || 'dev' }} --platform linux/arm64 module.tar.gz
